/* include/libchaos/config.h.  Generated by configure.  */
/* include/libchaos/config.h.in.  Generated from configure.in by autoheader.  */

/* Creation time of this server */
#define CREATION "Sun Oct 26 13:09:07 CET 2014"

/* Define your machines endian */
#define ENDIAN ENDIAN_LIL

/* Big endian machine */
#define ENDIAN_BIG 1

/* Little endian machine */
#define ENDIAN_LIL 0

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define this if you have freetype 2 */
/* #undef HAVE_FT2 */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the `crypto' library (-lcrypto). */
#define HAVE_LIBCRYPTO 1

/* Define to 1 if you have the `ssl' library (-lssl). */
#define HAVE_LIBSSL 1

/* Define to 1 if you have the `z' library (-lz). */
#define HAVE_LIBZ 1

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define this if you have MySQL */
#define HAVE_MYSQL "1"

/* Define to 1 if you have the <openssl/opensslv.h> header file. */
#define HAVE_OPENSSL_OPENSSLV_H 1

/* Define this if you have PostgreSQL */
/* #undef HAVE_PGSQL */

/* Define this if you have OpenSSL */
#define HAVE_SSL 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H */

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "libchaos"

/* Define to the release name of this package. */
#define PACKAGE_RELEASE "peace & love hippie edition"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libchaos 2.1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libchaos"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.1.0"

/* Platform this server runs on */
#define PLATFORM "Linux localhost.localdomain 3.11.10-301.fc20.x86_64 #1 SMP Thu Dec 5 14:01:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux"

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */
