#!/bin/sh
name="libsgui"
version="2.0.0rc4"

prefix="/usr/tichu"
exec_prefix="${prefix}"
includedir="${prefix}/include"
plugindir="@plugindir@"

CC=" cc"
INSTALL="../install"
CFLAGS="-Os -fexpensive-optimizations -fomit-frame-pointer -Wall -I$includedir -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/libpng16"
LIBS=" -lsgui -lSDL -lpthread -lpng16"

usage="\
Usage: $name-config [--prefix] [--exec-prefix] [--plugindir] 
                      [--version] [--cflags] [--libs] 
                      [--compile] [--install]
                        
   --prefix       Show prefix where $name is installed.
   --exec-prefix  Show prefix where $name executables are installed.
   --version      Show $name version.
   --cflags       Show compiler flags needed to compile a libsgui program.
   --libs         Show linker flags needed to link a libsgui program.
   --compile      Compiles a program using libsgui.
   --link         Links a program using libsgui.
"

if test $# -eq 0; then
	echo "${usage}" 1>&2
	exit 1
fi

while test $# -gt 0; do
	case "$1" in
	-*=*) 
		optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` 
		;;
	*) 
		optarg= 
		;;
	  esac

	case $1 in
	--prefix)
		echo $prefix
		;;
	--exec-prefix)
		echo $exec_prefix
		;;
	--plugindir)
		echo $plugindir
		;;
	--version)
		echo $version
		;;
	--cflags)
		echo $CFLAGS
		;;
	--libs)
		echo $LIBS
		;;
        --compile)
                shift
                
                if [ "x$1" = "x" ]
                then
                  echo "${usage}" 1>&2
                  exit 1
                fi
                
                src=`echo $1 | sed 's/\.c$//'`.c
                obj=`echo $1 | sed 's/\.c$//'`.o
                
                if [ ! -f $src ]
                then
                  echo "Source file $src not found."
                  break
                fi
                
                echo $CC $CFLAGS -o $obj -c $src
                $CC $CFLAGS -o $obj -c $src
                ;;
        --link)
                shift
                
                if [ "x$1" = "x" ]
                then
                  echo "${usage}" 1>&2
                  exit 1
                fi
                
                bin=`echo $1 | sed 's/\.o$//'`
                objs=""
                
                for o in $*
                do
                  shift
                
                  obj="`echo $o | sed 's/\.o$//'`.o"
                
                  if [ ! -f $obj ]
                  then
                    echo "Object file $obj not found."
                    break
                  fi
                  
                  objs="$objs $obj"
                done
                
                echo $CC -o $bin $objs $LIBS
                $CC -o $bin $objs $LIBS
                ;;
	    *)
		echo "${usage}" 1>&2
		exit 1
		;;
	esac
	shift
done

